---
# $Author$
# $Date$
# $Source$

# environment-facts tasks file for mdrotthoff.gather-facts

- name: Display the enter environment-facts.yml message
  debug:
    msg: 'Enter environment-facts.yml'
  tags:
  - debug
  - never

- name: Create the base output directory
  include_tasks: output-directory.yml
  when:
  - gather_facts_output_dir is not defined
  tags:
  - gather_facts

- name: Create the environment facts subdirectory if requested
  block:

  - name: Set the environment output directory
    set_fact:
      gather_facts_environment_dir: 'environment-facts/'

  - name: Ensure the environment output directory exists
    file:
      path:      "{{ gather_facts_output_dir }}{{ gather_facts_environment_dir }}"
      state:     directory
      recurse:   true
    connection:  local
    become:      false
  when:
  - gather_facts_directory_facts_type is defined
  - gather_facts_directory_facts_type

- name: Dump the environment facts in YAML format
  template:
    src:         host_facts_environment_yaml.j2
    dest:        "{{ gather_facts_output_dir }}{{ gather_facts_environment_dir | default('') }}{{ inventory_hostname }}.environment.yaml"
  connection:    local
  become:        false
  ignore_errors: "{{ ansible_check_mode }}"

- name: Display the exit environment-facts.yml message
  debug:
    msg: 'Exit environment-facts.yml'
  tags:
  - debug
  - never
