---
# $Author$
# $Date$
# $Source$

# host_facts_environment tasks file for mdrotthoff.gather-facts

- name: Create the environment facts subdirectory if requested
  block:

  - name: Set the environment output directory
    set_fact:
      gather_facts_environment_dir: 'environment/'

  - name: Ensure the environment output directory exists
    file:
      path:      "{{ gather_facts_output_dir }}{{ gather_facts_environment_dir }}"
      state:     directory
      recurse:   true
    connection:  local
    become:      false
  when:
  - gather_facts_directory_facts_type is defined
  - gather_facts_directory_facts_type

- name: Dump the host environment variables in YAML format
  template:
    src:         host_facts_environment_yaml.j2
    dest:        "{{ gather_facts_output_dir }}{{ gather_facts_environment_dir | default('') }}{{ inventory_hostname }}.environment.yaml"
  connection:    local
  become:        false
  ignore_errors: "{{ ansible_check_mode }}"
