---
# $Author$
# $Date$
# $Source$

# host_facts_groups tasks file for mdrotthoff.gather-facts

- name: Create the groups facts subdirectory if requested
  block:

  - name: Set the groups output directory
    set_fact:
      gather_facts_groups_dir: 'groups/'

  - name: Ensure the groups output directory exists
    file:
      path:      "{{ gather_facts_output_dir }}{{ gather_facts_groups_dir }}"
      state:     directory
      recurse:   true
    connection:  local
    become:      false
  when:
  - gather_facts_directory_facts_type is defined
  - gather_facts_directory_facts_type

- name: Dump the host group variables in YAML format
  template:
    src:         host_facts_groups_yaml.j2
    dest:        "{{ gather_facts_output_dir }}{{ gather_facts_groups_dir | default('') }}{{ inventory_hostname }}.groups.yaml"
  connection:    local
  become:        false
  ignore_errors: "{{ ansible_check_mode }}"
