---
# $Author$
# $Date$
# $Source$

# ansible_facts tasks file for mdrotthoff.gather-facts

- name: Gather the host facts
  setup:
  register: gather_facts_setup_results
  become:   true

- name: Set the ansible fact output directory
  set_fact:
    gather_facts_host_dir: "{{ gather_facts_host_facts_dir | default(gather_facts_destination) | default('facts') }}/{{ gather_facts_domain_dir | default('') }}"

- name: Ensure the host facts output directory exists
  file:
    path:      "{{ gather_facts_host_dir }}"
    state:     directory
    recurse:   true
  connection:  local
  become:      false

#- name: Dump all vars in JSON format
#  template:
#    src:  gather_facts_host_facts_json.j2
#    dest: "{{ gather_facts_host_dir }}{{ inventory_hostname }}.json"
#  connection:   local
#  become:       false
#  ignore_errors: true
#  when:
#  - gather_facts_setup_results is defined
#  - gather_facts_host_facts_json is defined
#  - gather_facts_host_facts_json

- name: Dump the host environment variables in YAML format
  template:
    src:  host_facts_environment_yaml.j2
    dest: "{{ gather_facts_host_dir }}{{ inventory_hostname }}.environment.yaml"
  connection:   local
  become:       false
  ignore_errors: true
  when:
  - gather_facts_setup_results is defined
  - gather_facts_host_facts_yaml is defined
  - gather_facts_host_facts_yaml

- name: Dump all group variables in YAML format
  template:
    src:  host_facts_groups_yaml.j2
    dest: "{{ gather_facts_host_dir }}{{ inventory_hostname }}.groups.yaml"
  connection:   local
  become:       false
  ignore_errors: true
  when:
  - gather_facts_setup_results is defined
  - gather_facts_host_facts_yaml is defined
  - gather_facts_host_facts_yaml

- name: Dump all host variables in YAML format
  template:
    src:  host_facts_host_vars_yaml.j2
    dest: "{{ gather_facts_host_dir }}{{ inventory_hostname }}.host-vars.yaml"
  connection:   local
  become:       false
  ignore_errors: true
  when:
  - gather_facts_setup_results is defined
  - gather_facts_host_facts_yaml is defined
  - gather_facts_host_facts_yaml

- name: Dump ansible variables in YAML format
  template:
    src:  host_facts_ansible_vars_yaml.j2
    dest: "{{ gather_facts_host_dir }}{{ inventory_hostname }}.ansible.yaml"
  connection:   local
  become:       false
  ignore_errors: true
  when:
  - gather_facts_setup_results is defined
  - gather_facts_host_facts_yaml is defined
  - gather_facts_host_facts_yaml
