---
# $Author$
# $Date$
# $Source$

# host_facts_groups tasks file for mdrotthoff.gather-facts

- name: Create the host variables facts subdirectory if requested
  block:

  - name: Set the host variables output directory
    set_fact:
      gather_facts_host_vars_dir: 'host-vars/'

  - name: Ensure the host variables output directory exists
    file:
      path:      "{{ gather_facts_output_dir }}{{ gather_facts_host_vars_dir }}"
      state:     directory
      recurse:   true
    connection:  local
    become:      false
  when:
  - gather_facts_directory_facts_type is defined
  - gather_facts_directory_facts_type

- name: Dump the host variables in YAML format
  template:
    src:         host_facts_host_vars_yaml.j2
    dest:        "{{ gather_facts_output_dir }}{{ gather_facts_host_vars_dir | default('') }}{{ inventory_hostname }}.host-vars.yaml"
  connection:    local
  become:        false
  ignore_errors: "{{ ansible_check_mode }}"
