---
# $Author$
# $Date$
# $Source$

# host-facts tasks file for mdrotthoff.gather-facts

- name: Display the enter host-facts.yml message
  debug:
    msg: 'Enter host-facts.yml'
  tags:
  - debug
  - never

- name: Create the base output directory
  include_tasks: output-directory.yml
  when:
  - gather_facts_output_dir is not defined
  tags:
  - gather_facts

- name: Create the host facts subdirectory if requested
  block:

  - name: Set the host variables output directory
    set_fact:
      gather_facts_host_vars_dir: 'host-facts/'

  - name: Ensure the host variables output directory exists
    file:
      path:      "{{ gather_facts_output_dir }}{{ gather_facts_host_vars_dir }}"
      state:     directory
      recurse:   true
    connection:  local
    become:      false
  when:
  - gather_facts_directory_facts_type is defined
  - gather_facts_directory_facts_type

- name: Dump the host facts in YAML format
  template:
    src:         host_facts_host_vars_yaml.j2
    dest:        "{{ gather_facts_output_dir }}{{ gather_facts_host_vars_dir | default('') }}{{ inventory_hostname }}.host-vars.yaml"
  connection:    local
  become:        false
  ignore_errors: "{{ ansible_check_mode }}"

- name: Display the exit host-facts.yml message
  debug:
    msg: 'Exit host-facts.yml'
  tags:
  - debug
  - never
