---
# $Author$
# $Date$
# $Source$

# main tasks file for mdrotthoff.gather-facts

- name: Display the enter main.yml message
  debug:
    msg: 'Enter main.yml'
  tags:
  - debug
  - never

- name: Output the environment facts if requested
  include_tasks: environment-facts.yml
  when:
  - gather_facts_environment_facts is defined
  - gather_facts_environment_facts
  tags:
  - gather_facts
  - host_enviroment_facts

- name: Output the group facts if requested
  include_tasks: group-facts.yml
  when:
  - gather_facts_group_facts is defined
  - gather_facts_group_facts
  tags:
  - gather_facts
  - host_group_facts

- name: Output the host facts if requested
  include_tasks: host-facts.yml
  when:
  - gather_facts_host_vars_facts is defined
  - gather_facts_host_vars_facts
  tags:
  - gather_facts
  - host_group_facts

- name: Output the ansible facts if requested
  include_tasks: ansible-facts.yml
  when:
  - gather_facts_ansible_vars_facts is defined
  - gather_facts_ansible_vars_facts
  tags:
  - gather_facts
  - host_ansible_facts

- name: Output the SSH facts if requested
  include_tasks: ssh-facts.yml
  when:
  - gather_facts_ssh_keys_facts is defined
  - gather_facts_ssh_keys_facts
  tags:
  - gather_facts
  - host_ssh_keys_facts

- name: Display the exit main.yml message
  debug:
    msg: 'Exit main.yml'
  tags:
  - debug
  - never
