---
# $Author$
# $Date$
# $Source$

# ssh-facts tasks file for mdrotthoff.gather-facts

- name: Display the enter ssh-facts.yml message
  debug:
    msg: 'Enter ssh-facts.yml'
  tags:
  - debug
  - never

- name: Create the base output directory
  include_tasks: output-directory.yml
  when:
  - gather_facts_output_dir is not defined
  tags:
  - gather_facts

- name:  Scan and register the host ssh keys
  command:      "ssh-keyscan {{ ansible_fqdn }}"
  register:     gather_facts_ssh_key_data
  changed_when: false
  connection:   local
  check_mode:   false

- name: Display the ssh keys data stdout lines
  debug:
    var: gather_facts_ssh_key_data.stdout_lines
  tags:
  - debug
  - never

- name: Display the individual ssh keys output lines
  debug:
    msg: "{{ item }}"
  loop: "{{ gather_facts_ssh_key_data.stdout_lines }}"
  tags:
  - debug
  - never

- name: Collect the SSH keys found
  set_fact:
    gather_facts_ssh_keys: "{{ gather_facts_ssh_keys|default([]) + [ {'ssh_key_type': item.split(' ')[1], 'ssh_key_value': item.split(' ')[2]} ] }}"
  loop: "{{ gather_facts_ssh_key_data.stdout_lines }}"

- name: Display the ssh keys gathered
  debug:
    var: gather_facts_ssh_keys
  tags:
  - debug
  - never

- name: Create the SSH facts subdirectory if requested
  block:
  - name: Set the SSH facts output directory
    set_fact:
      gather_facts_ssh_facts_dir: 'ssh-keys/'

  - name: Ensure the SSH keys output directory exists
    file:
      path:      "{{ gather_facts_output_dir }}{{ gather_facts_ssh_facts_dir }}"
      state:     directory
      recurse:   true
    connection:  local
    become:      false

  when:
  - gather_facts_directory_facts_type is defined
  - gather_facts_directory_facts_type

- name: Dump the SSH facts in YAML format
  template:
    src:         ssh-facts-yaml.j2
    dest:        "{{ gather_facts_output_dir }}{{ gather_facts_ssh_facts_dir | default('') }}{{ inventory_hostname }}.ssh-keys.yaml"
  connection:    local
  become:        false
  ignore_errors: "{{ ansible_check_mode }}"

- name: Display the exit ssh-facts.yml message
  debug:
    msg: 'Exit ssh-facts.yml'
  tags:
  - debug
  - never
