---
# $Author$
# $Date$
# $Source$

# ansible_facts tasks file for mdrotthoff.gather-facts

- name: Scan and register the host ssh keys
  command:      "ssh-keyscan {{ ansible_fqdn }}"
  register:     gather_facts_host_keys
  changed_when: false
  connection:   local
  check_mode:   false

- name: Collect the SSH keys found
  set_fact:
    gather_facts_ssh_keys: "{{ gather_facts_ssh_keys|default([]) + [ {'ssh_key_type': item.split(' ')[1], 'ssh_key_value': item.split(' ')[2]} ] }}"
  loop: "{{ gather_facts_host_keys.stdout_lines }}"

- name: Create the ssh_key_output variable
  set_fact:
    gather_facts_ssh_key_output: '{ "ssh_key_data": { "hostname": "{{ ansible_fqdn }}", "host_aliases": {{ ssh_key_aliases | default([]) }}, "ipv4_addresses": {{ ansible_all_ipv4_addresses | default([]) }}, "ipv6_addresses": {{ ansible_all_ipv6_addresses | default([]) }}, "ssh_keys": {{ gather_facts_ssh_keys | default([]) }} } }'

- name: Set the ansible SSH facts output directory
  set_fact:
    gather_facts_ssh_dir: "{{ gather_facts_ssh_facts_dir | default(gather_facts_destination) | default('facts') }}/{{ gather_facts_domain_dir | default('') }}"

- name: Ensure the SSH facts output directory exists
  file:
    path:      "{{ gather_facts_ssh_dir }}"
    state:     directory
    recurse:   true
  connection:  local
  become:      false

- name: Output the SSH key information to a JSON file
  template:
    src:         gather_facts_ssh_keys_json.j2
    dest:        "{{ gather_facts_ssh_dir }}{{ ansible_fqdn }}.ssh_keys.json"
    mode:        '0444'
  connection:    local
  become:        false
  when:          gather_facts_ssh_keys

- name: Output the SSH key information to a JSON file
  template:
    src:         gather_facts_ssh_keys_yaml.j2
    dest:        "{{ gather_facts_ssh_dir }}{{ ansible_fqdn }}.ssh_keys.yaml"
    mode:        '0444'
  connection:    local
  become:        false
  when:          gather_facts_ssh_keys
